name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

permissions: read-all

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          make test